In [1]:
a=[1.0,2.0,3.0]
a[0]

1.0

In [2]:
a[2]=4.0
a

[1.0, 2.0, 4.0]

In [3]:
import torch

In [8]:
a=torch.ones(3)
a[0] # 仍然是一个tensor

tensor(1.)

In [9]:
float(a[0]) # 转换成python的float类型

1.0

In [11]:
a[2]=2.0
a

tensor([1., 1., 2.])

In [14]:
points=torch.zeros(6) # 6个元素的向量
points[0]=4.0
points[1]=1.0
points[2]=5.0
points[3]=3.0
points[4]=2.0
points[5]=1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [16]:
points=torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0]) # 用python的list初始化tensor
points

tensor([4., 1., 5., 3., 2., 1.])

In [19]:
float(points[0])

4.0

In [20]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]]) # 3*2的矩阵
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [21]:
points.shape # 查看形状

torch.Size([3, 2])

In [23]:
points[0,0]

tensor(4.)

In [24]:
points[1,1]

tensor(3.)

In [ ]:
# storage

In [25]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])   
points


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [26]:
points.storage() # 一维的tensor

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage._TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [31]:
second_point=points[2]
second_point,second_point.storage_offset() # 从第几个元素开始

(tensor([2., 1.]), 4)

In [32]:
second_point.size(),second_point.shape # size是一个function,shape是一个attribute

(torch.Size([2]), torch.Size([2]))

In [33]:
second_point

tensor([2., 1.])

In [37]:
second_point[0]=10
second_point

tensor([10.,  1.])

In [38]:
print(points)
# 所以可以看见second_points使用的是points的storage

tensor([[ 4.,  1.],
        [ 5.,  3.],
        [10.,  1.]])


In [48]:
# 谨慎的赋值,新开辟的一段空间
another_point=points[1].clone()
another_point.storage_offset()

0

In [50]:
another_point[0]=20
another_point

tensor([20.,  3.])

In [51]:
points

tensor([[ 4.,  1.],
        [ 5.,  3.],
        [10.,  1.]])

In [52]:
second_point=points[1]
second_point

tensor([5., 3.])

In [53]:
second_point.stride() # 一维

(1,)

In [67]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 10.0
 1.0
[torch.storage._TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [68]:
points

tensor([[ 4.,  1.],
        [ 5.,  3.],
        [10.,  1.]])

In [54]:
points.stride() # 看内存中的存储方式 (行，列)

(2, 1)

In [57]:
points_t=points.t() # transforms 转置
points_t

tensor([[ 4.,  5., 10.],
        [ 1.,  3.,  1.]])

In [61]:
id(points.storage())==id(points_t.storage()) # 用的内存是同一块内存

True

In [65]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 10.0
 1.0
[torch.storage._TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [66]:
points_t.stride() # 

(1, 2)

In [72]:
some_t=torch.ones(3,4,5)
some_t.stride() #4*5 5 1  

(20, 5, 1)

In [74]:
transpose_t=some_t.transpose(0,2) # 第0维和第2维换一下

In [75]:
transpose_t.shape

torch.Size([5, 4, 3])

In [76]:
transpose_t.stride() # 

(1, 5, 20)

In [77]:
points.is_contiguous() # 是否是连续的

True

In [78]:
points_t.is_contiguous() # 跟内存的读的顺序不一样

False