In [2]:
import torch

In [13]:
# 三种方法
# 方法1：
# double_points=torch.ones(10,2,dtype=torch.double)
# short_points=torch.tensor([[1,2],[3,4]],dtype=torch.short)

# 方法2：
# double_points=torch.zeros(10,2).double()
# short_points=torch.ones(10,2).short()

# 方法3：
double_points=torch.zeros(10,2).to(torch.double)
# short_points=torch.ones(10,2).to(torch.short)
short_points=torch.ones(10,2).to(dtype=torch.short)

In [14]:
double_points.dtype,short_points.dtype

(torch.float64, torch.int16)

In [15]:
short_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [35]:
points_64=torch.rand(5,dtype=torch.double) # generate random numbers between 0 (inclusive) and 1 (exclusive)
points_short=points_64.to(torch.short) # 不是四舍五入，而是直接取整数
print(points_64)
points_short

tensor([0.7269, 0.9726, 0.0169, 0.6961, 0.5917], dtype=torch.float64)


tensor([0, 0, 0, 0, 0], dtype=torch.int16)

In [36]:
a=torch.tensor(1.1)
b=torch.tensor(1.9)
a_short=a.to(torch.short)
b_short=b.to(torch.short)
print(a_short,b_short)

tensor(1, dtype=torch.int16) tensor(1, dtype=torch.int16)


In [32]:
points_int=torch.randint(low=0, high=10, size=(5,8), dtype=torch.int) # 16位整数 随机生成
points_int

tensor([[3, 0, 4, 9, 3, 3, 7, 3],
        [6, 1, 4, 2, 9, 2, 6, 5],
        [9, 2, 0, 1, 5, 2, 4, 0],
        [7, 3, 0, 6, 4, 0, 8, 4],
        [3, 0, 5, 0, 0, 0, 5, 4]], dtype=torch.int32)

In [37]:
points_64*points_short # 两个tensor相乘，类型会自动转换为更高精度的类型

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)