In [8]:
import torch

In [9]:
some_list=list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [10]:
some_list[1:4]

[1, 2, 3]

In [11]:
point=torch.tensor([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
point

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [12]:
point[1] # 取出第一行
point[1:] # 第一行以后的所有行
point[1:,:] # 第一行以后的所有行，第一列以后的所有列
point[1:,0] # 第一行以后的所有行，第一列
point[None] # 增加一个维度 unsequeeze

tensor([[[1., 2.],
         [3., 4.],
         [5., 6.]]])

In [13]:
points=torch.ones(3,4)
points_np=points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [14]:
point=torch.from_numpy(points_np)
point

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## 文件读写

In [15]:
torch.save(point,"../data/p1ch3/ourpoints.t")

In [16]:
with open("../data/p1ch3/ourpoints.t","wb") as f:
    torch.save(point,f) # 保存到文件

In [17]:
a=torch.load("../data/p1ch3/ourpoints.t")
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
with open("../data/p1ch3/ourpoints.t","rb") as f:
    b=torch.load(f)
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
# !pip install h5py


In [20]:
import h5py

In [21]:
f=h5py.File("../data/p1ch3/new_ourpoints.hdf5","w")
dset=f.create_dataset("coords",data=points.numpy()) # 创建数据集 coords 是数据集的名称
f.close()

In [23]:
f=h5py.File("../data/p1ch3/new_ourpoints.hdf5","r")
dset=f["coords"]    # 读取数据集

In [24]:
dset

<HDF5 dataset "coords": shape (3, 4), type "<f4">

In [27]:
# last_points=dset[-2:] # 读取最后两行
last_points=dset[:] # 读取所有行
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [29]:
points=torch.tensor(dset[:])
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
last_points=torch.from_numpy(dset[-2:])
f.close() # 关闭文件

In [35]:
points=torch.tensor([[1.0,2.0],[3.0,4.0],[5.0,6.0]])    

In [36]:
torch.cuda.is_available() # 判断是否有GPU

True

In [37]:
points_gpu=torch.tensor([[1.0,2.0],[3.0,4.0],[5.0,6.0]],device="cuda") # 指定GPU

In [40]:
# points+points_gpu # CPU和GPU不能直接运算
points= points.to("cuda") # CPU转GPU
points+points_gpu # GPU和GPU可以直接运算

tensor([[ 2.,  4.],
        [ 6.,  8.],
        [10., 12.]], device='cuda:0')