# 给维度命名

In [1]:
import torch

In [2]:

img_t=torch.randn(3,5,5)
weights=torch.tensor([0.2126,0.7152,0.0722])

In [3]:
batch_t=torch.randn(2,3,5,5) # shape: batch, channel, height, width 

In [6]:
img_gray_naive=img_t.mean(-3) # 在第三个维度上求平均值
img_gray_naive.shape

torch.Size([5, 5])

In [8]:
batch_gray_naive=batch_t.mean(-3)
batch_gray_naive.shape

torch.Size([2, 5, 5])

In [11]:
weights = torch.tensor([0.2126, 0.7152, 0.0722]) # 使用加权平均值来计算灰度值
weights.shape

torch.Size([3])

In [14]:
# unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1) # 增加原来维度后面加两个维度就可以相乘了
unsqueezed_weights=weights.unsqueeze(-1)
print(unsqueezed_weights.shape)
unsqueezed_weights=unsqueezed_weights.unsqueeze(-1)
print(unsqueezed_weights.shape)


torch.Size([3, 1])
torch.Size([3, 1, 1])


In [15]:
img_weights=(img_t*unsqueezed_weights)
img_weights.shape

torch.Size([3, 5, 5])

In [16]:
batch_weights=(batch_t*unsqueezed_weights)
batch_weights.shape

torch.Size([2, 3, 5, 5])

In [17]:
img_gray_weighted=img_weights.sum(-3) # 在第三个维度上求和 为了得到灰度值
batch_gray_weighted=batch_weights.sum(-3)

In [18]:
batch_gray_weighted.shape

torch.Size([2, 5, 5])

In [19]:
img_t.shape,weights.shape

(torch.Size([3, 5, 5]), torch.Size([3]))

In [22]:
img_gray_weighted_fancy=torch.einsum('...chw,c->...hw',img_t,weights) # 把weights的维度和img_t的维度对应起来
img_gray_weighted_fancy.shape  # 将每个通道内的图像与相应的权重相乘，然后将它们相加，得到一个去除通道维度的新张量，因此结果的形状减少

torch.Size([5, 5])

In [23]:
batch_gray_weighted_fancy=torch.einsum('...chw,c->...hw',batch_t,weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [26]:
weights_namad=torch.tensor([0.2126,0.7152,0.0722],names=['channels'])
weights_namad

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [30]:
img_named=img_t.refine_names(...,'channels','rows','columns')
batch_named=batch_t.refine_names(...,'channels','rows','columns') # 从后往前给

In [29]:
img_named

tensor([[[ 0.6601,  0.2230,  0.6674, -0.4944, -1.4350],
         [ 0.9701, -0.1711,  0.1153, -1.0775,  0.3602],
         [ 0.0870, -0.8750, -0.6102,  1.2692,  0.4071],
         [ 0.9793,  0.2888, -1.0163, -1.3574, -0.1631],
         [ 0.8610,  1.1812,  1.4564,  0.3491,  0.3329]],

        [[ 0.5042, -0.4496,  1.5152, -0.4170,  0.9137],
         [-1.6535, -0.1679, -0.6943, -0.3424, -0.4489],
         [-0.2656,  0.3481, -0.0552,  0.5779, -0.9661],
         [ 0.3346,  0.1139, -0.7657,  0.6807, -2.3148],
         [ 1.2863, -1.0287, -1.4952, -0.5253, -1.3615]],

        [[-1.0186,  0.5063, -1.2710,  0.8188, -0.8087],
         [ 0.4512, -0.3054,  0.0461, -0.1154,  1.3052],
         [-2.5035, -0.1181,  0.4709,  1.2181, -0.3536],
         [-0.7204, -0.8581,  0.2327, -2.2518,  1.6194],
         [-0.1505,  2.1103, -0.1939,  0.3374, -1.0994]]],
       names=('channels', 'rows', 'columns'))

In [35]:
weights_aligned=weights_namad.align_as(img_named) # 使得维度对齐
weights_aligned

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]], names=('channels', 'rows', 'columns'))