In [4]:
import torch

In [5]:
a=torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
a_size=a.size() # 9
a_offset=a.storage_offset() # 0
a_stride=a.stride() # 步长
a_size,a_offset,a_stride

(torch.Size([9]), 0, (1,))

#1_a

In [7]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
b=a.view(3,3) # 相当于reshape,但是不会改变原来的tensor
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
# 查看内存地址
id(b.storage) == id(a.storage)

True

#1_b

In [11]:
c=b[1:,1:]
c

tensor([[4, 5],
        [7, 8]])

In [13]:
c.size(),c.storage_offset(),c.stride() # 和b的stride一样

(torch.Size([2, 2]), 4, (3, 1))

#2

In [15]:
a=torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
torch.cos(a)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [17]:
torch.sqrt(a) # 平方根

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])